"""
Explainability layer.

Turns the machine verdict + the signals actually bought into a short,
plain-language narrative for the business owner: what pattern the
evidence suggests in general terms, and — whenever the decision is not a
clean APPROVE — a concrete instruction to either verify the customer
manually through a secondary channel or discard the transaction outright.

No PII ever reaches the model: only signal names/status/coarse detail
(booleans, hour deltas, km deltas) are sent, never the MSISDN, declared
name, or any raw carrier payload field that could contain an identifier.
"""
import json
import logging
from typing import List, Tuple

import httpx

from app.config import settings
from app.schemas import SignalResult

logger = logging.getLogger("trust.explain")

# Only these detail keys are safe (non-identifying) to hand to the model.
# Anything else in a signal's `details` (carrier name, exact carrier
# ticket numbers, raw match scores tied to a specific person, etc.) is
# dropped before it ever reaches the prompt.
# NOTE on location retrieval: `delta_km`, `within_declared_area`,
# `accuracy_m` and `stale` are coarse, non-identifying derivations and are
# safe to send. The raw `latitude`/`longitude`/`serving_cell` the
# retrieval signal returns are a precise physical location for a real
# person and are deliberately NOT listed here, so they never reach the
# model — the narrative only ever learns "X km away", never where.
_SAFE_DETAIL_KEYS = {
    "swapped", "swap_hours", "match", "travel_plausible", "delta_km",
    "recycled", "reachable", "roaming", "verified", "recycled_date",
    "verification_result", "match_rate",
    "within_declared_area", "accuracy_m", "stale",
}


def _sanitize_signals(signals: List[SignalResult]) -> List[dict]:
    sanitized = []
    for sig in signals:
        safe_details = {k: v for k, v in sig.details.items() if k in _SAFE_DETAIL_KEYS}
        sanitized.append({"name": sig.name, "status": sig.status, "details": safe_details})
    return sanitized


_SYSTEM_PROMPT = (
    "You are a fraud-risk analyst writing a short note for a business owner "
    "who has no technical background. You are given a transaction verdict "
    "(APPROVE, REVIEW, HOLD, or REJECT) and the network-signal evidence "
    "behind it — never any phone number, name, or personal identifier.\n\n"
    "Write exactly two short paragraphs as plain text (no markdown, no "
    "headers):\n"
    "1) One or two sentences describing, in general non-technical terms, "
    "what pattern the evidence suggests about this transaction (e.g. "
    "consistent with a legitimate returning customer, or consistent with "
    "an account-takeover / SIM-swap pattern, or an unreachable/spoofed "
    "device) — do not invent details the signals don't support.\n"
    "2) A concrete recommendation for the business owner. If the decision "
    "is APPROVE, simply confirm it is safe to proceed. If it is REVIEW, "
    "HOLD, or REJECT, explicitly advise one of two concrete actions: "
    "manually verify the customer through a secondary, already-confirmed "
    "channel (e.g. a callback) before proceeding, OR discard/decline the "
    "transaction outright — pick whichever is proportionate to the "
    "severity and say so plainly, in one sentence.\n\n"
    "Never mention phone numbers, names, IDs, or any specific identifying "
    "detail — you were not given any. Keep the whole note under 80 words."
)


async def generate_explanation(
    decision: str, score: int, confidence: str,
    signals: List[SignalResult], override_rule_fired: str | None,
) -> Tuple[str, str] | None:
    """
    Returns (summary, recommended_action) generated by the LLM, or None if
    the LLM is unavailable/misconfigured/errors — callers should keep their
    existing deterministic templated text in that case.
    """
    if not settings.LLM_AGENT_ENABLED or not settings.OPENROUTER_API_KEY:
        return None

    payload_facts = {
        "decision": decision,
        "score": score,
        "confidence": confidence,
        "override_rule_fired": override_rule_fired,
        "signals": _sanitize_signals(signals),
    }

    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(payload_facts, default=str)},
    ]

    try:
        headers = {
            "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://trust.mena-ignite.local",
            "X-Title": "TRUST Verification Agent",
        }
        async with httpx.AsyncClient(timeout=20.0) as client:
            resp = await client.post(
                f"{settings.OPENROUTER_BASE_URL}/chat/completions",
                headers=headers,
                json={"model": settings.OPENROUTER_MODEL, "messages": messages, "temperature": 0.3},
            )
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"].strip()
    except (httpx.HTTPError, KeyError, IndexError) as exc:
        logger.warning("explanation generation failed, keeping templated text: %s", exc)
        return None

    paragraphs = [p.strip() for p in content.split("\n") if p.strip()]
    if not paragraphs:
        return None
    summary = paragraphs[0]
    recommended_action = paragraphs[1] if len(paragraphs) > 1 else paragraphs[0]
    return summary, recommended_action
